### PR TITLE
#184651345-Update-Product

### PR DESCRIPTION
**Pull request by ruberwa**
#### What does this PR do?
      * A seller should be able to update a product item from their collection

#### Description of Task to be completed?
    - Product has to be exist
    - Only owner can update product
    - Input has to be positive number
    - User get clear message of what is going on

#### How should this be manually tested?
  * Clone the branch
  * Go to its path in terminal run: npm install for Dependencies
  * Create .env file
  * Add the following Variables in that .env file
    - JWT_SECRET    - USER_SECRET_KEY    - BCRYPT_KEY
    - TOKEN_EXPIRATION    - SENDGRID_API_KEY    - SENDER_EMAIL
    - GOOGLE_CLIENT_ID    - GOOGLE_CLIENT_SECRET    - NODE_ENV
    - DB_USERNAME    - DB_PASSWORD    - DB_HOST
    - DB_NAME    - RESET_URL

  * Go to this URL to test functionalities: http://localhost:5000/api-docs/
  - Go to product conner:
      - Create admin's Account and Login to get token
      - Create user's Account and Login to get token
      - Create change user role to become seller with admin token
      - Create Login as seller to get token
      - Use seller token to create a product(s)
      - Get product id and seller token
        * Update product

#### What are the relevant pivotal tracker/Trello stories?
      * 184651345

### CODE REVIEW

**Review by kagame8732 — DISMISSED** [review]
Well implemented!

**Review by JulesNIYOMWUNGERI — DISMISSED** [review]
well!

**Review by nshutip — DISMISSED** [review]

**Review by JulesNIYOMWUNGERI — APPROVED** [review]
well done!

**Review by kagame8732 — APPROVED** [review]
Working effeciently !

**Pull request merged**
