### PR TITLE
#184651351-ft-clear-cart

### PR DESCRIPTION
**Pull request by ruberwa**
#### What does this PR do?
      * Buyers should be able to clear their cart

#### Description of Task to be completed?
      * A User who logged in is able to clear her/his item(s) in the cart.
    - User is not allowed to clear someone else's cart
    - Authenticated users only allowed to clear the cart

#### How should this be manually tested?
  * Clone the branch
  * Go to its path in the terminal run: npm install for Dependencies
  * Create a .env file
  * Add the following Variables in that .env file
    - JWT_SECRET
    - USER_SECRET_KEY
    - BCRYPT_KEY
    - TOKEN_EXPIRATION
    - SENDGRID_API_KEY
    - SENDER_EMAIL
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - NODE_ENV
    - DB_USERNAME
    - DB_PASSWORD
    - DB_HOST
    - DB_NAME
    - RESET_URL

  * Go to this URL to test functionalities: http://localhost:5000/api-docs/
  * Create an Account and Login
  * Create a product(s)
  * Add product(s) in the cart by product id
      * CLEAR THE CART

#### What are the relevant pivotal tracker/Trello stories?
      * 184651351

### CODE REVIEW

**Review by nshutip — DISMISSED** [review]
This PR is for clear cart functionality, but the changed files are all for the view cart functionality

**Review by nshutip — DISMISSED** [review]
Well implemented!

**Review by kagame8732 — DISMISSED** [review]

**Review by JulesNIYOMWUNGERI — DISMISSED** [review]
working well!

**Review by JulesNIYOMWUNGERI — DISMISSED** [review]
well!

**Review by kagame8732 — DISMISSED** [review]
Working well!

**Review by bstwagir — DISMISSED** [review]
The functionality is well implemented

**Review by kagame8732 — APPROVED** [review]
Working effeciently

**Review by JulesNIYOMWUNGERI — APPROVED** [review]
well

**Pull request merged**
