### PR TITLE
A user should be able to search a product-#184651352

### PR DESCRIPTION
**Pull request by JulesNIYOMWUNGERI**
#### What does this PR do?

- User is able to search a products by name, type,  price range(minPrice&maxPrice), or by combination of two or more 

#### Description of Task to be completed?

- User can search a specific products from database
- User can do this search by name of the products, or by type of the products, or by price range(minPrice&maxPrice)
- User can also do this search by combination of name & type, name & price range, type & price range, or name & type & price range

#### How should this be manually tested?

- Clone the branch
- Open it in your code editor
- Open terminal and run npm install, for installing dependencies
- Create .env file
- Add the following variables in that .env file

- PORT
- DB_USERNAME
- DB_PASSWORD
- DB_NAME
- DB_HOST
- NODE_ENV
- USER_SECRET_KEY
- DEVELOPMENT_DB
- SENDGRID_API_KEY
- SENDER_EMAIL
- TOKEN_EXPIRATION
- BCRYPT_KEY
- RESET_URL
- GOOGLE_CLIENT_SECRET
- GOOGLE_CLIENT_ID

- Run npm start, to start the server

- Go to this URL to test functionalities: http://localhost:PORT/api-docs/

#### What are the relevant pivotal tracker/Trello stories?

- #184651352

### CODE REVIEW

**Review by ruberwa — DISMISSED** [review]
Looks Good!

**Review by kagame8732 — DISMISSED** [review]
Working as we expected!!

**Review by bahati10 — DISMISSED** [review]
Looks good

**Review by Raphaela664 — DISMISSED** [review]

**Review by kagame8732 — APPROVED** [review]
Working as we expect!

**Review by Raphaela664 — APPROVED** [review]

**Pull request merged**
