### PR TITLE
#184651320 create PR Template

### PR DESCRIPTION
**Pull request by nshutip**
#### What does this PR do?

Creates an empty pull_request_template.md file, which contains a template to be used in the description of the changes proposed in a pull request.

#### What are the relevant pivotal tracker/Trello stories?

#184651320

### CODE REVIEW

**Review by kagame8732 — DISMISSED** [review]
I was wondering whether you could provide some clarifications.

**Review by Raphaela664 — DISMISSED** [review]

**Review by JulesNIYOMWUNGERI — DISMISSED** [review]
good

**Review by bahati10 — DISMISSED** [review]
- [x] Skeleton Done

**Review by furebo — CHANGES_REQUESTED** [review]
Consider squashing the commits to only one commit

**Review by heshima18 — APPROVED** [review]

**Pull request closed without merging**
