### PR TITLE
#184651340 A seller should be able to Create/Add a product to his collection

### PR DESCRIPTION
**Pull request by bstwagir**
#### What does this PR do?
Add create a product API endpoint

#### Description of Task to be completed?

Have the following endpoint working
POST /api/addProduct

##### PRE-REQUIRED:
======> .env

USER_SECRET_KEY= YOUR JWT SECRET KEY 
TOKEN_EXPIRATION= expiration time of the token
NODE_ENV= ENV YOU WANT YOU USE FROM YOUR CONFIG
DB_USERNAME= YOUR POSTGRES USERNAME
DB_PASSWORD= YOUR POSTGRES PASSWORD
DB_DEVELOPMENTDB=YOUR DATABASE NAME
DB_HOST=YOUR HOSTNAME

====> Needed

User in the database that has been granted seller's permissions.

====>
- Clone the repository 
- Navigate to the project 
- In the terminal type: ``npm install`` to install the required dependencies.
- RUN ``npm start``
- Using Postman test the endpoint above

#### What are the relevant pivotal tracker/Trello stories?
#184651340

### CODE REVIEW

**Review by ruberwa — DISMISSED** [review]
Looks good!

**Review by kagame8732 — DISMISSED** [review]
Working well!

**Review by JulesNIYOMWUNGERI — APPROVED** [review]
well done!

**Review by ruberwa — APPROVED** [review]
Looks Good!

**Pull request merged**
