### PR TITLE
Ft coveralls code coverage 184651324

### PR DESCRIPTION
**Pull request by ruberwa**
#### What does this PR do?
Integrate Coveralls code coverage service

#### Description of Task to be completed?

-  Sign up for a Coveralls account and generate an API key. https://coveralls.io/ 

-  Install the necessary NPM packages for code coverage. 
   npm install --save express nyc coveralls
   npm install --save-dev mocha chai 

- Sign up for a ciclici account and give coveralls API key environment variable. https://circleci.com/

- Set up your Node.js/Express application

- Configure CircleCI to run your tests and generate code coverage reports

- Add some sample tests using mocha and chai 

- configure .circleci/config.yml to upload the code coverage report to Coveralls using the generated API key 
- Verify that the code coverage report is being sent to Coveralls correctly and that you can view the coverage results on the Coveralls dashboard.

#### How should this be manually tested?
- Clone, 
- Navigate to the project 
- In the terminal type: npm install to install the required dependencies.
- for test coverage: npm run test

by running 'npm run test' you can see the coverage

#### What are the relevant pivotal tracker/Trello stories?
#184651324

### CODE REVIEW

**Review by bahati10 — DISMISSED** [review]

**Review by kagame8732 — DISMISSED** [review]

**Review by JulesNIYOMWUNGERI — DISMISSED** [review]
good

**Review by nshutip — DISMISSED** [review]
The PR description doesn't meet the engineering playbook standards.

**Review by bahati10 — DISMISSED** [review]

**Review by kagame8732 — DISMISSED** [review]

**Review by nshutip — DISMISSED** [review]
Well executed!

**Review by bahati10 — DISMISSED** [review]

**Review by kagame8732 — DISMISSED** [review]

**Review by bahati10 — DISMISSED** [review]

**Review by kagame8732 — DISMISSED** [review]

**Review by bstwagir — DISMISSED** [review]

**Review by nshutip — DISMISSED** [review]
Well executed!

**Review by bahati10 — DISMISSED** [review]

**Review by kagame8732 — APPROVED** [review]
Well resolved !!

**Review by bahati10 — APPROVED** [review]

**Review by furebo — APPROVED** [review]

**Pull request merged**
